### ISSUE TITLE
Binance bridge won't deploy

### ISSUE THREAD

**Issue by geohot** [cheapETH/bridge#6]
NETWORK=binance npx hardhat run scripts/bridge.js --network cheapeth

Giving error:
ProviderError: execution reverted: block in in the future

**Comment by Camisul** [comment]
Fixed? I'm syncing just fine, or at least it seem that way. But I had to set  gas limit manually, Wierd.
```
-      Bridge = await BridgeFactory.deploy(lib.getBlockRlp(genesis_block), validators);
+      Bridge = await BridgeFactory.deploy(lib.getBlockRlp(genesis_block), validators, { gasLimit: 5_000_000});
```
![image](https://user-images.githubusercontent.com/7963180/112577565-9b838300-8e05-11eb-805e-ab416413cb44.png)

**Comment by geohot** [comment]
Fixed with https://github.com/cheapETH/bridge/commit/6d8ed27d08ca2f4967afdbba27b76457ae96dd5c
